---
# File: install_remote.yml - package installation tasks for Consul

- name: Install OS packages
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ consul_os_packages }}"
  tags: installation

- name: Validate remote Consul directory
  file:
    path: /tmp/consul
    state: directory

- name: Read Consul package checksum file
  stat:
    path: "/tmp/consul/consul_{{ consul_version }}_SHA256SUMS"
  register: consul_checksum
  tags: installation

- name: Download Consul package checksum file
  get_url:
    url: "{{ consul_checksum_file_url }}"
    dest: "/tmp/consul/consul_{{ consul_version }}_SHA256SUMS"
    validate_certs: no
  tags: installation
  when: consul_checksum.stat.exists == False

- name: Read Consul package checksum
  shell: "grep {{ consul_pkg }} /tmp/consul/consul_{{ consul_version }}_SHA256SUMS"
  register: consul_sha256
  tags: installation

- name: Check Consul package file
  stat:
    path: "/tmp/consul/{{ consul_pkg }}"
  register: consul_package
  tags: installation

- name: Download Consul
  get_url:
    url: "{{ consul_zip_url }}"
    dest: "/tmp/consul/{{ consul_pkg }}"
    checksum: "sha256:{{ consul_sha256.stdout.split(' ')|first }}"
    timeout: 42
  tags: installation
  when: consul_package.stat.exists == False

- name: Unarchive Consul and install binary
  unarchive:
    remote_src: yes
    src: "/tmp/consul/{{ consul_pkg }}"
    dest: "{{ consul_bin_path }}"
    owner: "{{ consul_user }}"
    group: "{{ consul_group }}"
    mode: 0755
  tags: installation

- name: Cleanup
  file:
    path: "{{ item }}"
    state: absent
  with_fileglob: "/tmp/consul"
  tags: installation
