---
# File: tasks/Red Hat.yml - Red Hat tasks for Consul

- name: "Distribution specific variables"
  include_vars: "{{ ansible_distribution }}.yml"

# Download and install SELinux Python module (required by Ansible)  

- name: OS Packages
  yum: "name={{ item }} state=present"
  with_items: "{{ consul_redhat_os_packages }}"
  tags: installation

- name: Download Consul
  get_url: "url={{ consul_zip_url }} dest=/tmp/{{ consul_redhat_pkg }} sha256sum={{ consul_redhat_sha256 }} timeout=74"
  tags: installation

- name: Install Consul
  unarchive: "copy=no src=/tmp/{{ consul_redhat_pkg }} dest=/usr/local/bin/ owner={{ consul_user }} group={{ consul_group }} mode=0755"
  tags: installation

- name: Cleanup
  sudo: True
  shell: "rm -rf /tmp/{{ consul_redhat_pkg }}"
  tags: installation
