---
- name: Start consul on Unix
  become: true
  ansible.builtin.service:
    name: consul
    state: started
    # Needed to force SysV service manager on Docker for Molecule tests
    use: "{{ ansible_service_mgr }}"
  when:
    - ansible_os_family != "Darwin"
    - ansible_os_family != "Windows"
  listen: start consul

- name: Start consul on Mac
  ansible.builtin.include_tasks: "{{ role_path }}/handlers/start_consul_mac.yml"
  when: ansible_os_family == "Darwin"
  listen: start consul

- name: Start consul on Windows
  ansible.windows.win_service:
    name: consul
    state: started
  when: ansible_os_family == "Windows"
  listen: start consul
